[project]
name = "cgr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chemprop>=2.0.2",
    "dora-xgb>=1.10",
    "ergochemics",
    "hydra-core>=1.3.2",
    "hydra-submitit-launcher>=1.2.0",
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.5",
    "matplotlib>=3.10.1",
    "matplotlib-venn>=1.1.2",
    "minedatabase",
    "mlflow>=2.22.0",
    "nbformat>=5.10.4",
    "networkx>=3.4.2",
    "numpy>=2.2.4",
    "optuna>=4.3.0",
    "optuna-integration>=4.3.0",
    "pandas>=2.2.3",
    "plotly>=6.0.1",
    "polars>=1.31.0",
    "pyarrow>=19.0.1",
    "pydantic>=2.10.6",
    "rdkit>=2024.9.6",
    "scipy>=1.15.2",
    "torcheval>=0.0.7",
    "tqdm>=4.67.1",
]

[dependency-groups]
dev = []

[tool.uv.sources]
minedatabase = { git = "https://github.com/stefanpate/pickaxe.git", branch = "py_upgrade" }
ergochemics = { git = "https://github.com/stefanpate/ergochemics.git" }
