data:
  inner_splitter: true
  outer_split_idx: 1
  outer_splitter: 5
  split_seed: 1234
  split_strategy: random_rule_split
model:
  featurizer_mode: PROD_DIFF
  mp_d_h: 294
  mp_depth: 3
  pred_head_d_hs: []
  pred_head_name: linear
training:
  batch_size: 115
  final_lr: 0.001
  init_lr: 0.0001
  max_epochs: 32
  max_lr: 0.0001
  pw_scl: 0.8972273533012429
  warmup_epochs: 2
