data:
  inner_splitter: true
  outer_split_idx: 0
  outer_splitter: 5
  split_seed: 1234
  split_strategy: random_rule_split
model:
  featurizer_mode: PROD_DIFF
  mp_d_h: 283
  mp_depth: 3
  pred_head_d_hs:
  - 112
  - 200
  pred_head_name: ffn
training:
  batch_size: 114
  final_lr: 0.001
  init_lr: 0.0001
  max_epochs: 36
  max_lr: 0.0001
  pw_scl: 0.7354339392438477
  warmup_epochs: 2
