data:
  outer_split_idx: 1
  training_set: before_2020
model:
  ckpt: 650430769901274523/ec5bb121b65d4307ada72495e83ed9ad/artifacts/epoch=5-step=474/epoch=5-step=474.ckpt
  featurizer_mode: PROD_DIFF
  mp_d_h: 247
  mp_depth: 4
  pred_head_d_hs:
  - 156
  - 191
  - 117
  pred_head_name: ffn
training:
  batch_size: 109
  final_lr: 0.001
  init_lr: 0.0001
  max_epochs: 6
  max_lr: 0.0001
  pw_scl: 0.13466689503759408
  warmup_epochs: 2