data:
  outer_split_idx: 4
  training_set: before_2020
model:
  ckpt: 650430769901274523/3daed153cfc74a73a9a6cb922e506ee2/artifacts/epoch=4-step=380/epoch=4-step=380.ckpt
  featurizer_mode: PROD_DIFF
  mp_d_h: 293
  mp_depth: 4
  pred_head_d_hs:
  - 138
  - 167
  - 196
  pred_head_name: ffn
training:
  batch_size: 113
  final_lr: 0.001
  init_lr: 0.0001
  max_epochs: 5
  max_lr: 0.0001
  pw_scl: 0.2727668128480795
  warmup_epochs: 2