data:
  inner_splitter: true
  outer_split_idx: 4
  outer_splitter: true
  split_strategy: random_rule_split
model:
  ckpt: 335884163188429421/c968d902bc3e4811a937bc371ea488f6/artifacts/epoch=17-step=1278/epoch=17-step=1278.ckpt
  featurizer_mode: PROD_DIFF
  mp_d_h: 240
  mp_depth: 4
  pred_head_d_hs:
  - 200
  - 144
  - 156
  pred_head_name: ffn
training:
  batch_size: 115
  final_lr: 0.001
  init_lr: 0.0001
  max_epochs: 18
  max_lr: 0.0001
  pw_scl: 0.33502808999629763
  warmup_epochs: 2
