data:
  inner_splitter: true
  outer_split_idx: 0
  outer_splitter: true
  split_strategy: random_rule_split
model:
  ckpt: 935416590272618137/0e39101a0d7a47c084a26b5acb82443d/artifacts/epoch=6-step=560/epoch=6-step=560.ckpt
  featurizer_mode: PROD_DIFF
  mp_d_h: 211
  mp_depth: 4
  pred_head_d_hs:
  - 181
  - 103
  pred_head_name: ffn
training:
  batch_size: 102
  final_lr: 0.001
  init_lr: 0.0001
  max_epochs: 7
  max_lr: 0.0001
  pw_scl: 0.12624714905305276
  warmup_epochs: 2
