defaults:
  - filepaths: filepaths
  - _self_

mapped_rxns_fn: mapped_known_reactions_x_rc_plus_0_rules.parquet

hydra:
  run:
    dir: ${filepaths.rules}
  job:
    chdir: True
  sweep:
    dir: ${filepaths.rules}
    subdir: .
  sweeper:
    params:
      mapped_rxns_fn: >-
        mapped_known_reactions_x_mechinferred_dt_035_rules_before_2015_direct_mcsa_only.parquet,
        mapped_known_reactions_x_mechinferred_dt_059_rules_before_2015_direct_mcsa_only.parquet,
        mapped_known_reactions_x_mechinferred_dt_106_rules_before_2015_direct_mcsa_only.parquet,
        mapped_known_reactions_x_mechinferred_dt_244_rules_before_2015_direct_mcsa_only.parquet,
        mapped_known_reactions_x_mechinferred_dt_961_rules_before_2015_direct_mcsa_only.parquet
        