defaults:
  - filepaths: filepaths
  - _self_

dxgb:
  _target_: DORA_XGB.DORA_XGB.feasibility_classifier
  cofactor_positioning: add_concat

mfper:
  _target_: ergochemics.similarity.MorganFingerprinter
  radius: 3
  length: 1024
  mol_featurizer:
    _target_: ergochemics.similarity.MolFeaturizer

rc_dist_ub: 1

expansion_name: 2_steps_ccm_aa_aplusb_True
expansion_fns:
  - 2_steps_ccm_aa_rules_mechinformed_rules_w_coreactants_aplusb_True.pk
  - 2_steps_ccm_aa_rules_imt_rules_w_coreactants_aplusb_True.pk
  - 2_steps_ccm_aa_rules_mechinferred_dt_2_rules_w_coreactants_aplusb_True.pk 
  - 2_steps_ccm_aa_rules_mechinferred_dt_3_rules_w_coreactants_aplusb_True.pk
  - 2_steps_ccm_aa_rules_mechinferred_dt_6_rules_w_coreactants_aplusb_True.pk
  - 2_steps_ccm_aa_rules_mechinferred_dt_15_rules_w_coreactants_aplusb_True.pk
  - 2_steps_ccm_aa_rules_mechinferred_dt_98_rules_w_coreactants_aplusb_True.pk
  - 2_steps_ccm_aa_rules_rc_plus_0_rules_w_coreactants_aplusb_True.pk
  - 2_steps_ccm_aa_rules_rc_plus_1_rules_w_coreactants_aplusb_True.pk
  - 2_steps_ccm_aa_rules_rc_plus_2_rules_w_coreactants_aplusb_True.pk
  - 2_steps_ccm_aa_rules_rc_plus_3_rules_w_coreactants_aplusb_True.pk
  - 2_steps_ccm_aa_rules_rc_plus_4_rules_w_coreactants_aplusb_True.pk
expansion_name: 2_steps_ccm_aa_aplusb_True

hydra:
  run:
    dir: ${filepaths.processed_data}
  job:
    chdir: True
  sweep:
    dir: ${filepaths.processed_data}
    subdir: .