defaults:
  - filepaths: filepaths
  - _self_

dxgb:
  _target_: DORA_XGB.DORA_XGB.feasibility_classifier
  cofactor_positioning: add_concat

mfper:
  _target_: ergochemics.similarity.MorganFingerprinter
  radius: 3
  length: 1024
  mol_featurizer:
    _target_: ergochemics.similarity.MolFeaturizer

rc_dist_ub: 1

expansion_name: 2_steps_250728_benchmark_starters_aplusb_True

expansion_fns:
  - 2_steps_250728_benchmark_starters_rules_mechinformed_rules_w_coreactants_aplusb_True.pk
  - 2_steps_250728_benchmark_starters_rules_mechinferred_dt_01_rules_w_coreactants_aplusb_True.pk 
  - 2_steps_250728_benchmark_starters_rules_mechinferred_dt_02_rules_w_coreactants_aplusb_True.pk
  - 2_steps_250728_benchmark_starters_rules_mechinferred_dt_04_rules_w_coreactants_aplusb_True.pk
  - 2_steps_250728_benchmark_starters_rules_mechinferred_dt_13_rules_w_coreactants_aplusb_True.pk
  - 2_steps_250728_benchmark_starters_rules_mechinferred_dt_91_rules_w_coreactants_aplusb_True.pk
  - 2_steps_250728_benchmark_starters_rules_rc_plus_1_rules_w_coreactants_aplusb_True.pk
  - 2_steps_250728_benchmark_starters_rules_rc_plus_2_rules_w_coreactants_aplusb_True.pk
  - 2_steps_250728_benchmark_starters_rules_rc_plus_3_rules_w_coreactants_aplusb_True.pk
  - 2_steps_250728_benchmark_starters_rules_rc_plus_4_rules_w_coreactants_aplusb_True.pk

mapped_rxns_fns:
  - mapped_known_reactions_x_mechinformed_rules.parquet
  - mapped_known_reactions_x_mechinferred_dt_01_rules.parquet 
  - mapped_known_reactions_x_mechinferred_dt_02_rules.parquet
  - mapped_known_reactions_x_mechinferred_dt_04_rules.parquet
  - mapped_known_reactions_x_mechinferred_dt_13_rules.parquet
  - mapped_known_reactions_x_mechinferred_dt_91_rules.parquet
  - mapped_known_reactions_x_rc_plus_1_rules.parquet
  - mapped_known_reactions_x_rc_plus_2_rules.parquet
  - mapped_known_reactions_x_rc_plus_3_rules.parquet
  - mapped_known_reactions_x_rc_plus_4_rules.parquet

hydra:
  run:
    dir: ${filepaths.processed_data}
  job:
    chdir: True
  sweep:
    dir: ${filepaths.processed_data}
    subdir: .