defaults:
  - filepaths: filepaths
  - _self_

dxgb:
  _target_: DORA_XGB.DORA_XGB.feasibility_classifier
  cofactor_positioning: add_concat

mfper:
  _target_: cgr.featurize.MorganFingerprinter
  radius: 3
  length: 1024
  mol_featurizer:
    _target_: cgr.featurize.MolFeaturizer

rc_dist_ub: 1

expansion_name: test # 2_steps_ccm_aa_aplusb_True
expansion_fns:
  - 1_steps_ccm_aa_rules_rc_plus_4_rules_w_coreactants_aplusb_True.pk
  # - 2_steps_ccm_aa_rules_mechinformed_rules_w_coreactants_aplusb_True.pk
  # - 2_steps_ccm_aa_rules_imt_rules_w_coreactants_aplusb_True.pk
  # - 2_steps_ccm_aa_rules_mechinferred_dt_2_rules_w_coreactants_aplusb_True.pk 
  # - 2_steps_ccm_aa_rules_mechinferred_dt_3_rules_w_coreactants_aplusb_True.pk
  # - 2_steps_ccm_aa_rules_mechinferred_dt_6_rules_w_coreactants_aplusb_True.pk
  # - 2_steps_ccm_aa_rules_mechinferred_dt_15_rules_w_coreactants_aplusb_True.pk
  # - 2_steps_ccm_aa_rules_mechinferred_dt_98_rules_w_coreactants_aplusb_True.pk
  # - 2_steps_ccm_aa_rules_rc_plus_0_rules_w_coreactants_aplusb_True.pk
  # - 2_steps_ccm_aa_rules_rc_plus_1_rules_w_coreactants_aplusb_True.pk
  # - 2_steps_ccm_aa_rules_rc_plus_2_rules_w_coreactants_aplusb_True.pk
  # - 2_steps_ccm_aa_rules_rc_plus_3_rules_w_coreactants_aplusb_True.pk
  # - 2_steps_ccm_aa_rules_rc_plus_4_rules_w_coreactants_aplusb_True.pk
mapped_rxns_fns:
  - mapped_sprhea_240310_v3_mapped_no_subunits_x_rc_plus_4_rules.parquet
  # - mapped_sprhea_240310_v3_mapped_no_subunits_x_mechinformed_rules.parquet
  # - mapped_sprhea_240310_v3_mapped_no_subunits_x_imt_rules.parquet
  # - mapped_sprhea_240310_v3_mapped_no_subunits_x_mechinferred_dt_2_rules.parquet 
  # - mapped_sprhea_240310_v3_mapped_no_subunits_x_mechinferred_dt_3_rules.parquet
  # - mapped_sprhea_240310_v3_mapped_no_subunits_x_mechinferred_dt_6_rules.parquet
  # - mapped_sprhea_240310_v3_mapped_no_subunits_x_mechinferred_dt_15_rules.parquet
  # - mapped_sprhea_240310_v3_mapped_no_subunits_x_mechinferred_dt_98_rules.parquet
  # - mapped_sprhea_240310_v3_mapped_no_subunits_x_rc_plus_0_rules.parquet
  # - mapped_sprhea_240310_v3_mapped_no_subunits_x_rc_plus_1_rules.parquet
  # - mapped_sprhea_240310_v3_mapped_no_subunits_x_rc_plus_2_rules.parquet
  # - mapped_sprhea_240310_v3_mapped_no_subunits_x_rc_plus_3_rules.parquet
  # - mapped_sprhea_240310_v3_mapped_no_subunits_x_rc_plus_4_rules.parquet

hydra:
  run:
    dir: ${filepaths.processed_data}
  job:
    chdir: True
  sweep:
    dir: ${filepaths.processed_data}
    subdir: .