defaults:
  - filepaths: filepaths
  - override hydra/job_logging: custom
  - override hydra/launcher: quest_cpu
  - _self_

starters: ccm_aa
generations: 1
rules: mechinferred_dt_2_rules_w_coreactants
coreactants: metacyc_coreactants
processes: 1
a_plus_b: True

hydra:
  run:
    dir: ${filepaths.interim_data}
  job:
    chdir: True
  sweep:
    dir: ${filepaths.interim_data}
    subdir: .