defaults:
  - filepaths: filepaths
  - override hydra/job_logging: custom
  # - override hydra/launcher: quest_cpu
  - _self_

starters: after_2015_cpds
generations: 1
rules: evodex_Em_debug
coreactants: metacyc_coreactants
processes: 1
a_plus_b: true
explicit_h: false
enforce_atom_balance: true
block_inorganic: true

hydra:
  run:
    dir: ${filepaths.expansions}
  job:
    chdir: true
  sweep:
    dir: ${filepaths.expansions}
    subdir: .
  sweeper:
    params:
      rules: mechinferred_dt_2_rules_w_coreactants,mechinferred_dt_3_rules_w_coreactants,mechinferred_dt_6_rules_w_coreactants