defaults:
  - filepaths: filepaths
  - override hydra/job_logging: custom
  - override hydra/launcher: quest_cpu
  - _self_

starters: ccm_aa
generations: 2
rules: mechinferred_dt_2_rules_w_coreactants
coreactants: metacyc_coreactants
processes: ${hydra:launcher.cpus_per_task}
a_plus_b: True

hydra:
  run:
    dir: ${filepaths.interim_data}
  job:
    chdir: True
  sweep:
    dir: ${filepaths.interim_data}
    subdir: .
  sweeper:
    params:
      rules: mechinferred_dt_2_rules_w_coreactants,mechinferred_dt_3_rules_w_coreactants,mechinferred_dt_6_rules_w_coreactants