defaults:
  - filepaths: filepaths
  - training: base
  - data: random_rule_split
  - override hydra/job_logging: custom
  - override hydra/launcher: quest_gpu
  - _self_

n_trials: 3
timeout: 60
seed: 1234
study_name: "outer_split_${data.outer_split_idx}_strategy_${data.split_strategy}_obj_val_loss"

hp_bounds:
  model:
    mp_d_h: 
      values: [25, 500]
      type: int_log
    mp_depth:
      values: [1, 5]
      type: int
    pred_head_name:
      values: ['linear', 'ffn']
      type: categorical
    pred_head_d_h:
      values: [25, 500]
      type: int_log
    pred_head_depth:
      values: [1, 3]
      type: int
    featurizer_mode:
      values: ["PROD_DIFF", "REAC_PROD"]
      type: categorical
  training:
    batch_size:
      values: [32, 256]
      type: int_log
    max_epochs:
      values: [4, 5]
      type: int

hydra:
  run:
    dir: ${filepaths.artifacts}/hpo_conf/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True
  sweep:
    dir: ${filepaths.artifacts}/hpo_conf/${now:%Y-%m-%d}/${now:%H-%M-%S}