defaults:
  - filepaths: filepaths
  - training: base
  - data: random_rule_split
  - override hydra/job_logging: custom
  - override hydra/launcher: quest_cpu
  - _self_

n_trials: 100
seed: 1234
timeout: 36000
study_version: 0
objective: val_f1
direction: maximize # maximize | minimize
study_name: "outer_split_${data.outer_split_idx}_strategy_${data.split_strategy}_obj_${.objective}_v${.study_version}"

hp_bounds:
  model:
    mp_d_h: 
      values: [200, 300]
      type: int
    mp_depth:
      values: [3, 4]
      type: int
    pred_head_name:
      values: ['linear', 'ffn']
      type: categorical
    pred_head_d_h:
      values: [100, 200]
      type: int
    pred_head_depth:
      values: [2, 3]
      type: int
    featurizer_mode:
      values: ["PROD_DIFF"]
      type: categorical
  training:
    batch_size:
      values: [100, 120]
      type: int
    max_epochs:
      values: [5, 40]
      type: int
    init_lr:
      values: [0.0001, 0.0001]
      type: float
    final_lr:
      values: [0.001, 0.001]
      type: float
    max_lr:
      values: [0.0001, 0.0001]
      type: float
    pw_scl:
      values: [0.1, 2.0]
      type: float

hydra:
  run:
    dir: ${filepaths.artifacts}/hpo_conf/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True
  sweep:
    dir: ${filepaths.artifacts}/hpo_conf/${now:%Y-%m-%d}/${now:%H-%M-%S}