defaults:
  - filepaths: filepaths
  - training: base
  - data: random_rule_split
  - override hydra/job_logging: custom
  - override hydra/launcher: quest_cpu
  - _self_

n_trials: 50
seed: 1234
timeout: 18000
study_version: 0
objective: val_f1
direction: maximize # maximize | minimize
study_name: "outer_split_${data.outer_split_idx}_strategy_${data.split_strategy}_obj_${.objective}_v${.study_version}"

hp_bounds:
  model:
    mp_d_h: 
      values: [200, 400]
      type: int_log
    mp_depth:
      values: [1, 4]
      type: int
    pred_head_name:
      values: ['linear', "ffn"]
      type: categorical
    pred_head_d_h:
      values: [50, 300]
      type: int_log
    pred_head_depth:
      values: [1, 3]
      type: int
    featurizer_mode:
      values: ["REAC_PROD", "REAC_DIFF", "PROD_DIFF"]
      type: categorical
  training:
    batch_size:
      values: [64, 128]
      type: int_log
    max_epochs:
      values: [25, 50]
      type: int
    init_lr:
      values: [0.0001, 0.0001]
      type: float
    final_lr:
      values: [0.001, 0.001]
      type: float
    max_lr:
      values: [0.0001, 0.0001]
      type: float
    pw_scl:
      values: [0.33, 3]
      type: float

hydra:
  run:
    dir: ${filepaths.artifacts}/hpo_conf/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True
  sweep:
    dir: ${filepaths.artifacts}/hpo_conf/${now:%Y-%m-%d}/${now:%H-%M-%S}