defaults:
  - filepaths: filepaths
  - _self_

k: 3
max_n: 50
rule_id: decarb
src_file: decarbs.parquet
input_path: ${filepaths.raw_data}/${src_file}

hydra:
  run:
    dir: ${filepaths.interim_data}
  job:
    chdir: True