defaults:
  - filepaths: filepaths
  - production: outer_split_0
  - override hydra/job_logging: custom
  - _self_

training: ${production.training}
data: ${production.data}
model: ${production.model}

hydra:
  run:
    dir: ${filepaths.artifacts}/pred_conf/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True
  sweep:
    dir: ${filepaths.artifacts}/pred_conf/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweeper:
    params:
      production: outer_split_0,outer_split_1,outer_split_2,outer_split_3,outer_split_4