defaults:
  - filepaths: filepaths
  - production: before_2020_0
  - override hydra/job_logging: custom
  - _self_

training: ${production.training}
data: ${production.data}
model: ${production.model}

hydra:
  run:
    dir: ${filepaths.artifacts}/pred_conf/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True
  sweep:
    dir: ${filepaths.artifacts}/pred_conf/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweeper:
    params:
      production: before_2020_0,before_2020_1,before_2020_2,before_2020_3,before_2020_4