defaults:
  - filepaths: filepaths
  - _self_

k: 3 # Max k for k-hop subgraph collecting
max_n: 50 # Number atoms in largest subgraph
N_ave: 22 # Average # rxns mapped by min op
rule_id: 1023
src_file: mapped_sprhea_240310_v3_mapped_no_subunits_x_min_rules.parquet
input_path: ${filepaths.raw_data}/${src_file}
xref: True # Whether to cross-reference w/ mechanistic
ds: 2 # Downsample factor

hydra:
  run:
    dir: ${filepaths.interim_data}/${...rule_id}
  job:
    chdir: True