defaults:
  - filepaths: filepaths
  - _self_

fields:
  - mcsa_id
  - enzyme_name
  - reference_uniprot_id
  - is_reference_uniprot_id
  - description
  - protein
  - all_ecs
  - reaction
  - mechanisms

url: https://www.ebi.ac.uk/thornton-srv/m-csa/api/entries/?format=json

hydra:
  run:
    dir: ${filepaths.raw_data}
  job:
    chdir: True