defaults:
  - filepaths: filepaths
  - override hydra/job_logging: custom
  - _self_

expansion: ???
min_mapped_rxns: 10

hydra:
  run:
    dir: ${filepaths.interim_data}/std_pickaxe_rxns
  job:
    chdir: True
  sweep:
    dir: ${filepaths.interim_data}/std_pickaxe_rxns
    subdir: .
