defaults:
  - filepaths: filepaths
  - training: base
  - override hydra/job_logging: custom
  - _self_

hydra:
  run:
    dir: ${filepaths.artifacts}/models
  job:
    chdir: True
  sweep:
    dir: ${filepaths.artifacts}
    subdir: models