defaults:
  - filepaths: filepaths
  - training: base
  - data: random_split
  - model: linear_pred_base
  - override hydra/job_logging: custom
  - _self_

study_name: "outer_split_${data.outer_split_idx}_strategy_${data.split_strategy}_obj_val_loss"
use_study: False

hydra:
  run:
    dir: ${filepaths.artifacts}/train_conf/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True
  sweep:
    dir: ${filepaths.artifacts}/train_conf/${now:%Y-%m-%d}/${now:%H-%M-%S}