defaults:
  - filepaths: filepaths
  - training: base
  - data: random_rule_split
  - model: ffn_pred_base
  - override hydra/job_logging: custom
  - override hydra/launcher: quest_cpu
  - _self_

# These determine the hpo result to use
use_study: False # Do use hpo result
study_version: 0
objective: val_f1
study_name: "outer_split_${data.outer_split_idx}_strategy_${data.split_strategy}_obj_${.objective}_v${.study_version}"

do_calibrate: False
calibration_fraction: 0.15
experiment_name: "outer_splits" # Determines location of output - model, preds, artifacts

hydra:
  run:
    dir: ${filepaths.artifacts}/train_conf/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True
  sweep:
    dir: ${filepaths.artifacts}/train_conf/${now:%Y-%m-%d}/${now:%H-%M-%S}