defaults:
  - filepaths: filepaths
  - training: base
  - data: random_rule_split
  - model: linear_pred_base
  - override hydra/job_logging: custom
  - override hydra/launcher: quest_cpu
  - _self_

use_study: False
study_version: 0
objective: val_auprc
study_name: "outer_split_${data.outer_split_idx}_strategy_${data.split_strategy}_obj_${.objective}_v${.study_version}"

hydra:
  run:
    dir: ${filepaths.artifacts}/train_conf/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True
  sweep:
    dir: ${filepaths.artifacts}/train_conf/${now:%Y-%m-%d}/${now:%H-%M-%S}