defaults:
  - filepaths: filepaths
  - _self_

rule_id: decarb
subgraph_instances: subgraph_instances.parquet
binary_feature_matrix: bfm.npy
frequency_lb_scl: 10

hydra:
  run:
    dir: ${filepaths.processed_data}
  job:
    chdir: True