defaults:
  - filepaths: filepaths
  - _self_

src_file: mapped_known_reactions_x_rc_plus_0_rules.parquet
R: 1

hydra:
  run:
    dir: ${filepaths.processed_data}
  job:
    chdir: True
  sweep:
    dir: ${filepaths.processed_data}
    subdir: .