defaults:
  - submitit_slurm

<<<<<<< HEAD
timeout_min: 120
=======
timeout_min: 36030
>>>>>>> 091d4a8d1ff1aa65772993f7a66a5a4ba2fa3338
account: b1039
partition: b1039
mem_gb: 24
nodes: 1
tasks_per_node: 1
cpus_per_task: 1